version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
        - db
    volumes:
      - ./backend:/var/www/app
      - ./docker/backend/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  db:
      image: mysql:9.0.1
      container_name: db
      restart: always
      ports:
        - '3306:3306'
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE:
          MYSQL_USER:
          MYSQL_PASSWORD:
      networks:
          - app-network

#  vue:
#    build:
#      context: ./path_to_vue
#      dockerfile: Dockerfile
#    volumes:
#      - ./path_to_vue:/app
#    networks:
#      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx/cert/:/etc/ssl/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/app
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
volumes:
  mysql_data:
networks:
  app-network:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 1450
